# This is a basic workflow to help you get started with Actions

name: comment

# Controls when the action will run. 
on:
  issue_comment: 
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    if: contains(github.event.comment.body, '/comment')
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - name: Find Comment
    #   uses: peter-evans/find-comment@v1
    #   id: fc
    #   with:
    #     token: ${{ secrets.MY_GITHUB_TOKEN }}
    #     issue-number: ${{ github.event.pull_request.number }}
        # comment-author: 'github-actions[bot]'
        # body-includes: This comment was written by a bot!

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: 1
        # issue-number: ${{ github.event.pull_request.number }}
        body: |
          This comment was written by a bot!
        reactions: rocket

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          This comment has been updated!
        reactions: hooray
