# This is a basic workflow to help you get started with Actions

name: comment

# Controls when the action will run. 
on:
  issue_comment: 
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reply:
    if: contains(github.event.comment.body, '/comment')
    runs-on: ubuntu-latest

    steps:
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          This comment was written by a bot!
        reactions: rocket
