# This is a basic workflow to help you get started with Actions

name: issue

# Controls when the action will run. 
on:
  issue_comment: 
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CloseIssue:
    if: contains(github.event.comment.body, '/close')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Change issue title
      run: |
        python change_issue_title.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
